## Checking trained logistic regression model on new data

In [4]:
import numpy as np
import pandas as pd
import joblib
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from pathlib import Path

In [5]:
DATA_PATH = Path('data')/'test.csv'

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f'Data File not Found {DATA_PATH.resolve()}'
    )

df = pd.read_csv(DATA_PATH)

In [6]:
df.head()

   Unnamed: 0     id  ... Arrival Delay in Minutes             satisfaction
0           0  19556  ...                     44.0                satisfied
1           1  90035  ...                      0.0                satisfied
2           2  12360  ...                      0.0  neutral or dissatisfied
3           3  77959  ...                      6.0                satisfied
4           4  36875  ...                     20.0                satisfied

[5 rows x 25 columns]

In [8]:
df = df.drop(columns=['Unnamed: 0','id'])

In [9]:
df.head()

   Gender      Customer Type  ...  Arrival Delay in Minutes             satisfaction
0  Female     Loyal Customer  ...                      44.0                satisfied
1  Female     Loyal Customer  ...                       0.0                satisfied
2    Male  disloyal Customer  ...                       0.0  neutral or dissatisfied
3    Male     Loyal Customer  ...                       6.0                satisfied
4  Female     Loyal Customer  ...                      20.0                satisfied

[5 rows x 23 columns]

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             25976 non-null  str
 1   Customer Type                      25976 non-null  str
 2   Age                                25976 non-null  int64
 3   Type of Travel                     25976 non-null  str
 4   Class                              25976 non-null  str
 5   Flight Distance                    25976 non-null  int64
 6   Inflight wifi service              25976 non-null  int64
 7   Departure/Arrival time convenient  25976 non-null  int64
 8   Ease of Online booking             25976 non-null  int64
 9   Gate location                      25976 non-null  int64
 10  Food and drink                     25976 non-null  int64
 11  Online boarding                    25976 non-null  int64
 12  Seat comfort                       25976 non-null  int64
 13  Inflight entertainment             25976 non-null  int64
 14  On-board service                   25976 non-null  int64
 15  Leg room service                   25976 non-null  int64
 16  Baggage handling                   25976 non-null  int64
 17  Checkin service                    25976 non-null  int64
 18  Inflight service                   25976 non-null  int64
 19  Cleanliness                        25976 non-null  int64
 20  Departure Delay in Minutes         25976 non-null  int64
 21  Arrival Delay in Minutes           25893 non-null  float64
 22  satisfaction                       25976 non-null  str
dtypes: float64(1), int64(17), str(5)
memory usage: 4.6 MB

In [11]:
df['satisfaction'] = df['satisfaction'].map({
    'neutral or dissatisfied':0,
    'satisfied':1
})

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = df.drop(columns=['satisfaction'])
y = df['satisfaction']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,stratify=y,random_state=40)

In [15]:
trained_model = joblib.load('logistic-reg_trained')

In [16]:
ypred_trained = trained_model.predict(X_train)

In [17]:
ypred_test = trained_model.predict(X_test)

In [18]:
print(f'accuracy score of X train data - {accuracy_score(y_train,ypred_trained)}')

accuracy score of X train data - 0.8724082934609251

In [20]:
print(f'accuracy score of X train data - {accuracy_score(y_test,ypred_test)}')

accuracy score of X train data - 0.8711664314128064

In [21]:
print('Classification Report of X train data')
print(classification_report(y_train,ypred_trained))

Classification Report of X train data
              precision    recall  f1-score   support

           0       0.87      0.90      0.89     10201
           1       0.87      0.83      0.85      7982

    accuracy                           0.87     18183
   macro avg       0.87      0.87      0.87     18183
weighted avg       0.87      0.87      0.87     18183

In [22]:
print('Classification Report of X test data')
print(classification_report(y_test,ypred_test))

Classification Report of X test data
              precision    recall  f1-score   support

           0       0.87      0.90      0.89      4372
           1       0.87      0.83      0.85      3421

    accuracy                           0.87      7793
   macro avg       0.87      0.87      0.87      7793
weighted avg       0.87      0.87      0.87      7793